config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "reviews#index"
  # カテゴリー検索ルート
  get '/reviews/displacement/:id', to: "reviews#displacement"
  get '/reviews/maker/:id', to: "reviews#maker"
  get '/reviews/type/:id', to: "reviews#type"
  # いいね機能ルート
  post   '/like/:review_id' => 'likes#like',   as: 'like'
  delete '/like/:review_id' => 'likes#unlike', as: 'unlike'
  resources :reviews do
    collection do
      get 'search'
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :displacement, :maker, :type]
  before_action :find_review, only: [:show, :edit, :update, :destroy]
  before_action :no_reload, only: [:destroy]
  before_action :search_reviews, only: [:index, :search]

  def index
    @user = User.new
    @reviews = Review.includes({image_attachment: :blob}).order('created_at DESC').page(params[:page]).per(5)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      flash[:posted] = "投稿が完了しました"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @review.comments.includes(:user)
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to review_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    review = Review.find(params[:id])
    if review.destroy
      flash[:delete] = "レビューの削除が完了しました"
      redirect_to root_path
    end
  end

  def search
    @results = @r.result.includes({image_attachment: :blob}).order('created_at DESC')
  end

  def displacement
    @review = Review.find_by(displacement_id: params[:id])
    @reviews = Review.where(displacement_id: params[:id]).includes({image_attachment: :blob}).order('created_at DESC')
  end

  def maker
    @review = Review.find_by(maker_id: params[:id])
    @reviews = Review.where(maker_id: params[:id]).includes({image_attachment: :blob}).order('created_at DESC')
  end

  def type
    @review = Review.find_by(type_id: params[:id])
    @reviews = Review.where(type_id: params[:id]).includes({image_attachment: :blob}).order('created_at DESC')
  end

  private
  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(
      :bike, :year, :displacement_id, :maker_id, :type_id,
      :recommend, :comfort, :fuel, :maintenance, :cost,
      :speed, :look, :content, :image).merge(user_id: current_user.id)
  end

  def no_reload
    if request.path_info != session[:ref]
      # 通常時の処理
      session[:ref] = request.path_info
   else
      redirect_to root_path
   end
  end

  def search_reviews
    @r = Review.ransack(params[:q])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_comments_area.html.erb
<% if user_signed_in? %>
  <%= form_with(model: [@review, @comment], local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div>
    <%= f.text_area :text, placeholder:"ライダーに質問やコメントなどをしてみましょう", class: :comment_text %>
  </div>
    <%= f.submit "コメントする", class: :comment_btn %>
    </div>
  <% end %>
<% end %>
<ul class="comments-lists">
  <% @comments.reverse_each do |comment| %>
    <li class="comments-list">
      <%= link_to comment.user.nickname, user_path(comment.user), class: "comment-user" %>さん
      <a class="comment-text"><%= comment.text %>
      <a class="comment-time"><%= l comment.created_at %>
      <% if user_signed_in? && current_user.id == comment.user_id %>
        <%= link_to "削除", review_comment_path(@review, comment), data: {confirm: "コメントを削除してもよろしいですか？"}, method: :delete, class: "comment-delete-btn" %>
      <% end %>
    </li>
  <% end %> 
</ul>

app/views/reviews/_review.html.erb
<li class='list'>
  <%= link_to review_path(review.id) do %>
  <div class='review-img-content'>
    <% if review.image.attached? %>
      <%= image_tag review.image, class: "review-img" %>
    <% else %>
      <%= image_tag "noimage.png", class: "review-img" %>
    <% end %>
  </div>

  <div class='review-info'>
    <div class='review-name'>
      <%= review.bike %>
    </div>
    <div class='review-recommend-eval'>
      <span class="recommend-eval-text">総合評価</span>
      <div id="star-rate-<%= review.id %>"></div>
    </div>
  </div>
  <% end %>
</li>

<script>
  $('#star-rate-<%= review.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= review.recommend %>,
  });
</script>

app/views/reviews/_reviews_page.html.erb
<h2 class='title'>All Reviews</h2>
<ul class='review-lists'>
  <%= render partial: 'review', collection: @reviews %>
</ul>
<%= paginate @reviews, remote: true %>

app/views/reviews/displacement.html.erb
<%= render "shared/second_header" %>
<div class="search-result-content">
  <% if @reviews.length !=0 %>
    <div class="category-result-title">
      <%= "#{@review.displacement.name}の一覧ページ" %>
    </div>
    <ul class='review-lists'>
      <%  @reviews.each do |review| %>
        <li class='list'>
          <%= link_to review_path(review.id) do %>
          <div class='review-img-content'>
            <% if review.image.attached? %>
              <%= image_tag review.image, class: "review-img" %>
            <% else %>
              <%= image_tag "noimage.png", class: "review-img" %>
            <% end %>
          </div>

          <div class='review-info'>
            <div class='review-name'>
              <%= review.bike %>
            </div>
            <div class='review-recommend-eval'>
              <span class="recommend-eval-text">総合評価</span>
              <div id="star-rate-<%= review.id %>"></div>
            </div>
          </div>
          <% end %>
        </li>

        <script>
          $('#star-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.recommend %>,
          });
        </script>
      <% end %>
    </ul>

  <% else %>
    <div class="noresult">該当するレビューはありません</div>
  <% end %>
  <br>
  <%= link_to 'トップページへ戻る', root_path, class:"redirect-btn" %>
</div>

app/views/reviews/edit.html.erb
<%= render "shared/second_header" %>

<div class="bike-review-contents">

  <div class="post-review-main">
    <h2 class="post-review-title">レビュー編集</h2>
    <%= form_with(model: @review, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# バイク画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        <span class="optional">任意</span>
        お気に入りの写真
      </div>
      <div id="image-list"></div>
      <div class="click-upload">
        <p>
          お気に入りの写真があれば共有しましょう！
        </p>
        <%= f.file_field :image, id:"bike-image" %>
      </div>
    </div>
    <%# /バイク画像 %>

    <div class="bike-prof">
      <div class="weight-bold-text">
        車種名
      </div>
      <%= f.text_area :bike, class:"bike-text", id:"item-name", placeholder:"必須　20文字まで", maxlength:"20" %>
      <span>※アルファベット表記にすると他のユーザーがあなたのレビューを探しやすくなります</span>
    </div>
    <div class="bike-prof">
      <div class="weight-bold-text">
        年式
      </div>
      <%= f.text_area :year, class:"bike-text", id:"item-name", placeholder:"必須　例)2021" %>
      <span>※西暦(4桁)のみ・半角数字でご入力ください</span>
    </div>

    <%# レビューActiveHash %>
    <div class="bike-detail-hash">
        <div class="hash-box">
          <div class="weight-bold-text">
            排気量
          </div>
          <%= f.collection_select(:displacement_id, Displacement.all, :id, :name, {}, class:"select-box") %>
        </div>
        <div class="hash-box">
          <div class="weight-bold-text">
            メーカー
          </div>
          <%= f.collection_select(:maker_id, Maker.all, :id, :name, {}, class:"select-box") %>
        </div>
        <div class="hash-box">
          <div class="weight-bold-text">
            車種タイプ
          </div>
          <%= f.collection_select(:type_id, Type.all, :id, :name, {}, class:"select-box") %>
        </div>
    </div>
    <%# /レビューActiveHash %>

    <%# 星評価 %>
    <div class="bike-star-eval">
      <div class="star-edit-group">
        <%= f.label :comfort,'乗り心地　　　', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-comf-<%= @review.id %>"></div>
      </div>
      <div class="star-edit-group">
        <%= f.label :fuel,'燃費　　　　　', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-fuel-<%= @review.id %>"></div>
      </div>
      <div class="star-edit-group">
        <%= f.label :maintenance,'メンテナンス性', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-mainte-<%= @review.id %>"></div>
      </div>
      <div class="star-edit-group">
        <%= f.label :cost,'維持費　　　　', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-cost-<%= @review.id %>"></div>
      </div>
      <div class="star-edit-group">
        <%= f.label :speed,'速度　　　　　', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-speed-<%= @review.id %>"></div>
      </div>
      <div class="star-edit-group">
        <%= f.label :look,'見た目の満足度', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-look-<%= @review.id %>"></div>
      </div>
      <div class="star-edit-group">
        <%= f.label :recommend,'総合評価　　　', class:'weight-bold-text star-title' %>
        <div class="detail-value", id="edit-reco-<%= @review.id %>"></div>
      </div>
    </div>
    <%# /星評価 %>

    <%# レビューコメント %>
      <div class="bike-content">
        <div class="weight-bold-text">レビュー</div>
        <%= f.text_area :content, class:"bike-text", id:"bike-info",
        placeholder:"必須　最大1,000文字まで",rows:"9" ,maxlength:"1000" %>
      </div>
    <%# /レビューコメント %>

    <%# 下部ボタン %>
    <div class="post-btn-contents">
      <%= f.submit "更新する", class:"post-btn" %>
      <%=link_to 'もどる', review_path(params[:id]), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <!-- 星評価javascript -->
<%= render "shared/star_eval" %>

</div>

<%= render "shared/second_footer" %>

app/views/reviews/index.html.erb
<%= render "shared/header" %>
<div class='main'>
<%= render 'shared/flash_messages' %>
  <%# 画面上部のトップ写真部分 %>
  <div class='title-contents'>
    <div class='title-text'>
      <h2 class='service-title'>
        BIKKE!! -ONLY THAT RIDER KNOWS-
      </h2>
      <p class='service-explain'>
        -ライダーにしかわからないことがある-
      </p>
      <p class='service-explain'>
        BIKKE!!はあなたのバイク探しをお手伝いします
      </p>
    </div>
    <% unless user_signed_in? %>
      <%= form_with model: @user, url: user_session_path, class: 'top-session', local: true do |f| %>
        <%= f.email_field :email, class:"top-input-signin", id:"email", placeholder:"email" %>
        <%= f.password_field :password, class:"top-input-signin", id:"password", placeholder:"password" %>
        <div class='top-signin-btn'>
          <%= f.submit "sign in" ,class:"top-signin-white-btn" %>
        </div>
        <div class="top-info-text-signup">
          会員登録がまだの人は<span><%= link_to "こちら", new_user_registration_path %></span>
        </div>
      <% end %>
    <% end %>
  </div>
  <%# /画面上部のトップ写真部分  %>
  <%# 検索部分 %>
<%= render "shared/search-list" %>
  <%# 検索部分 %>
  <%# レビュー一覧 %>
  <div class='review-contents', id="reviews-page">
    <h2 class='title'>All Reviews</h2>
    <ul class='review-lists'>
      <%= render partial: 'review', collection: @reviews %>
    </ul>
    <%= paginate @reviews, remote: true %>
  </div>
  <%# レビュー一覧 %>
</div>
<%= render "shared/footer" %>

app/views/reviews/index.js.erb
  $('#reviews-page').html("<%= escape_javascript(render 'reviews_page', review: @reviews) %>");

app/views/reviews/maker.html.erb
<%= render "shared/second_header" %>

<div class="search-result-content">
  <% if @reviews.length !=0 %>
    <div class="category-result-title">
      <%= "#{@review.maker.name}の一覧ページ" %>
    </div>
    <ul class='review-lists'>
      <%  @reviews.each do |review| %>
        <li class='list'>
          <%= link_to review_path(review.id) do %>
          <div class='review-img-content'>
            <% if review.image.attached? %>
              <%= image_tag review.image, class: "review-img" %>
            <% else %>
              <%= image_tag "noimage.png", class: "review-img" %>
            <% end %>
          </div>

          <div class='review-info'>
            <div class='review-name'>
              <%= review.bike %>
            </div>
            <div class='review-recommend-eval'>
              <span class="recommend-eval-text">総合評価</span>
              <div id="star-rate-<%= review.id %>"></div>
            </div>
          </div>
          <% end %>
        </li>

        <script>
          $('#star-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.recommend %>,
          });
        </script>
      <% end %>
    </ul>

  <% else %>
    <div class="noresult">該当するレビューはありません</div>
  <% end %>
  <br>
  <%= link_to 'トップページへ戻る', root_path, class:"redirect-btn" %>
</div>

app/views/reviews/new.html.erb
<%= render "shared/second_header" %>

<div class="bike-review-contents">
  <div class="post-review-main">
    <h2 class="post-review-title">レビュー投稿</h2>
    <%= form_with(model: @review, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# バイク画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        <span class="optional">任意</span>
        お気に入りの写真
      </div>
      <div id="image-list"></div>
      <div class="click-upload">
        <p>
          お気に入りの写真があれば共有しましょう！
        </p>
        <%= f.file_field :image, id:"bike-image" %>
      </div>
    </div>
    <%# /バイク画像 %>

    <div class="bike-prof">
      <div class="weight-bold-text">
        車種名
      </div>
      <%= f.text_area :bike, class:"bike-text", id:"item-name", placeholder:"必須　20文字まで", maxlength:"20" %>
      <span>※アルファベット表記にすると他のユーザーがあなたのレビューを探しやすくなります</span>
    </div>
    <div class="bike-prof">
      <div class="weight-bold-text">
        年式
      </div>
      <%= f.text_area :year, class:"bike-text", id:"item-name", placeholder:"必須　例)2021" %>
      <span>※西暦(4桁のみ)・半角数字でご入力ください</span>
    </div>

    <%# レビューActiveHash %>
    <div class="bike-detail-hash">
        <div class="hash-box">
          <div class="weight-bold-text">
            排気量
          </div>
          <%= f.collection_select(:displacement_id, Displacement.all, :id, :name, prompt: '---') %>
        </div>
        <div class="hash-box">
          <div class="weight-bold-text">
            メーカー
          </div>
          <%= f.collection_select(:maker_id, Maker.all, :id, :name, prompt: '---') %>
        </div>
        <div class="hash-box">
          <div class="weight-bold-text">
            車種タイプ
          </div>
          <%= f.collection_select(:type_id, Type.all, :id, :name, prompt: '---') %>
        </div>
    </div>
    <%# /レビューActiveHash %>

    <%# 星評価 %>
    <div class="bike-star-eval">
      <div class="star-form-group" id="star1">
        <%= f.label :comfort,'乗り心地　　　', class:'weight-bold-text star-title' %>
      </div>
      <div class="star-form-group" id="star2">
        <%= f.label :fuel,'燃費　　　　　', class:'weight-bold-text star-title' %>
      </div>
      <div class="star-form-group" id="star3">
        <%= f.label :maintenance,'メンテナンス性', class:'weight-bold-text star-title' %>
      </div>
      <div class="star-form-group" id="star4">
        <%= f.label :cost,'維持費　　　　', class:'weight-bold-text star-title' %>
      </div>
      <div class="star-form-group" id="star5">
        <%= f.label :speed,'速度　　　　　', class:'weight-bold-text star-title' %>
      </div>
      <div class="star-form-group" id="star6">
        <%= f.label :look,'見た目の満足度', class:'weight-bold-text star-title' %>
      </div>
      <div class="star-form-group" id="star7">
        <%= f.label :recommend,'総合評価　　　', class:'weight-bold-text star-title' %>
      </div>
      <!-- 星評価javascript -->
      <%= render "shared/star_eval_new" %>
    </div>
    <%# /星評価 %>

    <%# レビューコメント %>
      <div class="bike-content">
        <div class="weight-bold-text">レビュー</div>
        <%= f.text_area :content, class:"bike-text", id:"bike-info",
        placeholder:"必須　最大1,000文字まで",rows:"9" ,maxlength:"1000" %>
      </div>
    <%# /レビューコメント %>

    <%# 下部ボタン %>
    <div class="post-btn-contents">
      <%= f.submit "投稿する", class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

<%= render "shared/second_footer" %>

app/views/reviews/search.html.erb
<%= render "shared/second_header" %>
<div class="search-result-content">
  <h1>
  検索結果
  </h1>

  <% if @results.length !=0 %>
    <ul class='review-lists'>
      <%  @results.each do |review| %>
        <li class='list'>
          <%= link_to review_path(review.id) do %>
          <div class='review-img-content'>
            <% if review.image.attached? %>
              <%= image_tag review.image, class: "review-img" %>
            <% else %>
              <%= image_tag "noimage.png", class: "review-img" %>
            <% end %>
          </div>

          <div class='review-info'>
            <div class='review-name'>
              <%= review.bike %>
            </div>
            <div class='review-recommend-eval'>
              <span class="recommend-eval-text">総合評価</span>
              <div id="star-rate-<%= review.id %>"></div>
            </div>
          </div>
          <% end %>
        </li>

        <script>
          $('#star-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.recommend %>,
          });
        </script>
      <% end %>
    </ul>

  <% else %>
    <div class="noresult">該当するレビューはありません</div>
  <% end %>
  <br>
  <%= link_to 'トップページへ戻る', root_path, class:"redirect-btn" %>
</div>

app/views/reviews/show.html.erb
<%= render "shared/second_header" %>
<%= render 'shared/flash_messages' %>
<div class="review-show">
  <div class="review-box">
    <div class="review-img-content">
      <% if @review.image.attached? %>
        <%= image_tag @review.image, class:"review-box-img" %>
      <% else %>
        <%= image_tag "noimage.png", class:"review-box-img" %>
      <% end %>
    </div>
    <div class="review-prof-box">
      <div class="review-title">基本情報</div>
      <div class="review-bike-states">
        <%= "ライダー　　： #{@review.user.nickname}" %>
      </div>
      <div class="review-bike-states">
        <%= "車種名　　　： #{@review.bike}" %>
      </div>
      <div class="review-bike-states">
        <%= "年式　　　　： #{@review.year}" %>
      </div>
      <div class="review-bike-states">
        <%= "排気量　　　： #{@review.displacement.name}" %>
      </div>
      <div class="review-bike-states">
        <%= "メーカー　　： #{@review.maker.name}" %>
      </div>
      <div class="review-bike-states">
        <%= "車種タイプ　： #{@review.type.name}" %>
      </div>
    </div>
    <div class='recommend-eval'>
      <span class="eval-text">総合評価</span>
      <div id="star-reco-<%= @review.id %>"></div>
      <div class="eval-star"><%= @review.recommend %>/5点</div>
    </div>
    <div class="review-explain-box">
      <div class="review-content">
        レビュー概要
      </div>
      <div><%= @review.content %></div>
    </div>

    <div class="review-star-eval">
      <div class="star-group">
        <div class="detail-review">乗り心地　　　</div>
        <div class="detail-value", id="star-comf-<%= @review.id %>"></div>
        <div class="eval-star"><%= @review.comfort %>/5点</div>
      </div>
      <div class="star-group">
        <div class="detail-review">燃費　　　　　</div>
        <div class="detail-value", id="star-fuel-<%= @review.id %>"></div>
        <div class="eval-star"><%= @review.fuel %>/5点</div>
      </div>
      <div class="star-group">
        <div class="detail-review">メンテナンス性</div>
        <div class="detail-value", id="star-mainte-<%= @review.id %>"></div>
        <div class="eval-star"><%= @review.maintenance %>/5点</div>
      </div>
      <div class="star-group">
        <div class="detail-review">維持費　　　　</div>
        <div class="detail-value", id="star-cost-<%= @review.id %>"></div>
        <div class="eval-star"><%= @review.cost %>/5点</div>
      </div>
      <div class="star-group">
        <div class="detail-review">速度　　　　　</div>
        <div class="detail-value", id="star-speed-<%= @review.id %>"></div>
        <div class="eval-star"><%= @review.speed %>/5点</div>
      </div>
      <div class="star-group">
        <div class="detail-review">見た目の満足度</div>
        <div class="detail-value", id="star-look-<%= @review.id %>"></div>
        <div class="eval-star"><%= @review.look %>/5点</div>
      </div>
    </div>
    <%# 星評価表示 %>
    <%= render "shared/star_eval" %>

    <%# お気に入り %>
    <% if user_signed_in? && current_user.id != @review.user_id %>
      <%= render partial: 'likes/like', review: @review %>
    <% end %>

    <%# 編集・削除ボタン %>
    <div class="edit-delete-group">
      <% if user_signed_in? && current_user.id == @review.user_id %>
        <%= link_to "編集", edit_review_path, class: "review-edit-btn" %>
        <%= link_to "削除", review_path(@review.id), method: :delete, class:"review-destroy", data: {confirm: "レビューを削除しますか？"} %>
      <% end %>
    </div>
    <%# /編集・削除ボタン %>
    <%# コメント %>
    <div class="comment-box">
        <%= render "comments_area" %>
    </div>
    <%# /コメント部分%>
  </div>
</div>
  <%# /レビューの概要 %>

<%= render "shared/second_footer" %>

app/views/reviews/type.html.erb
<%= render "shared/second_header" %>

<div class="search-result-content">
  <% if @reviews.length !=0 %>
    <div class="category-result-title">
      <%= "#{@review.type.name}の一覧ページ" %>
    </div>
    <ul class='review-lists'>
      <%  @reviews.each do |review| %>
        <li class='list'>
          <%= link_to review_path(review.id) do %>
          <div class='review-img-content'>
            <% if review.image.attached? %>
              <%= image_tag review.image, class: "review-img" %>
            <% else %>
              <%= image_tag "noimage.png", class: "review-img" %>
            <% end %>
          </div>

          <div class='review-info'>
            <div class='review-name'>
              <%= review.bike %>
            </div>
            <div class='review-recommend-eval'>
              <span class="recommend-eval-text">総合評価</span>
              <div id="star-rate-<%= review.id %>"></div>
            </div>
          </div>
          <% end %>
        </li>

        <script>
          $('#star-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= review.recommend %>,
          });
        </script>
      <% end %>
    </ul>

  <% else %>
    <div class="noresult">該当するレビューはありません</div>
  <% end %>
  <br>
  <%= link_to 'トップページへ戻る', root_path, class:"redirect-btn" %>
</div>